// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error)
	ListAllShops(ctx context.Context) ([]Shop, error)
	ListShopsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Shop, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
}

var _ Querier = (*Queries)(nil)
