// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shops.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createShop = `-- name: CreateShop :one
INSERT INTO shops (name, address, owner_id, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, address, owner_id, is_active, created_at, updated_at
`

type CreateShopParams struct {
	Name     string    `json:"name"`
	Address  *string   `json:"address"`
	OwnerID  uuid.UUID `json:"owner_id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.Name,
		arg.Address,
		arg.OwnerID,
		arg.IsActive,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.OwnerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, name, address, owner_id, is_active, created_at, updated_at FROM shops WHERE id = $1 AND is_active = true LIMIT 1
`

func (q *Queries) GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.OwnerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllShops = `-- name: ListAllShops :many
SELECT id, name, address, owner_id, is_active, created_at, updated_at FROM shops ORDER BY created_at DESC
`

func (q *Queries) ListAllShops(ctx context.Context) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listAllShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shop{}
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.OwnerID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopsByOwner = `-- name: ListShopsByOwner :many
SELECT id, name, address, owner_id, is_active, created_at, updated_at FROM shops WHERE owner_id = $1 AND is_active = true ORDER BY created_at DESC
`

func (q *Queries) ListShopsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShopsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shop{}
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.OwnerID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops
SET name = COALESCE($2, name),
    address = COALESCE($3, address),
    is_active = COALESCE($4, is_active),
    updated_at = now()
WHERE id = $1
RETURNING id, name, address, owner_id, is_active, created_at, updated_at
`

type UpdateShopParams struct {
	ID       uuid.UUID `json:"id"`
	Name     *string   `json:"name"`
	Address  *string   `json:"address"`
	IsActive *bool     `json:"is_active"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.IsActive,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.OwnerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
