// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]Permission, error)
	GetUserPermissionsInShop(ctx context.Context, arg GetUserPermissionsInShopParams) ([]Permission, error)
	GetUserRoleInShop(ctx context.Context, arg GetUserRoleInShopParams) (Role, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRolesByShop(ctx context.Context, shopID pgtype.UUID) ([]Role, error)
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
}

var _ Querier = (*Queries)(nil)
