// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_shop_roles (user_id, shop_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, shop_id) DO UPDATE SET role_id = EXCLUDED.role_id
`

type AssignUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	ShopID uuid.UUID `json:"shop_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.ShopID, arg.RoleID)
	return err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (name, description, module)
VALUES ($1, $2, $3)
RETURNING id, name, description, module, created_at
`

type CreatePermissionParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Module      string  `json:"module"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Name, arg.Description, arg.Module)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Module,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (shop_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, shop_id, name, description, is_active, created_at, updated_at
`

type CreateRoleParams struct {
	ShopID      pgtype.UUID `json:"shop_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.ShopID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, shop_id, name, description, is_active, created_at, updated_at FROM roles WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.name, p.description, p.module, p.created_at 
FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionsInShop = `-- name: GetUserPermissionsInShop :many
SELECT p.id, p.name, p.description, p.module, p.created_at
FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
JOIN user_shop_roles ur ON rp.role_id = ur.role_id
WHERE ur.user_id = $1 AND ur.shop_id = $2
`

type GetUserPermissionsInShopParams struct {
	UserID uuid.UUID `json:"user_id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) GetUserPermissionsInShop(ctx context.Context, arg GetUserPermissionsInShopParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getUserPermissionsInShop, arg.UserID, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleInShop = `-- name: GetUserRoleInShop :one
SELECT r.id, r.shop_id, r.name, r.description, r.is_active, r.created_at, r.updated_at
FROM roles r
JOIN user_shop_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1 AND ur.shop_id = $2
`

type GetUserRoleInShopParams struct {
	UserID uuid.UUID `json:"user_id"`
	ShopID uuid.UUID `json:"shop_id"`
}

func (q *Queries) GetUserRoleInShop(ctx context.Context, arg GetUserRoleInShopParams) (Role, error) {
	row := q.db.QueryRow(ctx, getUserRoleInShop, arg.UserID, arg.ShopID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, description, module, created_at FROM permissions ORDER BY module, name
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByShop = `-- name: ListRolesByShop :many
SELECT id, shop_id, name, description, is_active, created_at, updated_at FROM roles WHERE shop_id = $1 OR shop_id IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListRolesByShop(ctx context.Context, shopID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions WHERE role_id = $1 AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}
