// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProductStock = `-- name: AddProductStock :one
UPDATE products
SET stock = stock + $1
WHERE id = $2
RETURNING id, name, image_url, price, stock, created_at, updated_at, deleted_at, cost_price, shop_id
`

type AddProductStockParams struct {
	Quantity int32     `json:"quantity"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) AddProductStock(ctx context.Context, arg AddProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, addProductStock, arg.Quantity, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
		&i.ShopID,
	)
	return i, err
}

const assignProductCategory = `-- name: AssignProductCategory :exec
INSERT INTO product_categories (product_id, category_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignProductCategoryParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	CategoryID int32     `json:"category_id"`
}

func (q *Queries) AssignProductCategory(ctx context.Context, arg AssignProductCategoryParams) error {
	_, err := q.db.Exec(ctx, assignProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const checkCategoryExists = `-- name: CheckCategoryExists :one
SELECT EXISTS(SELECT 1 FROM categories WHERE id = $1)
`

func (q *Queries) CheckCategoryExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, checkCategoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const clearProductCategories = `-- name: ClearProductCategories :exec
DELETE FROM product_categories WHERE product_id = $1
`

func (q *Queries) ClearProductCategories(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearProductCategories, productID)
	return err
}

const countDeletedProducts = `-- name: CountDeletedProducts :one
SELECT count(*) FROM products p
WHERE
    ($1::int IS NULL OR EXISTS (SELECT 1 FROM product_categories pc WHERE pc.product_id = p.id AND pc.category_id = $1))
  AND
    ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%')
  AND ($3::uuid IS NULL OR p.shop_id = $3)
  AND p.deleted_at IS NOT NULL
`

type CountDeletedProductsParams struct {
	CategoryID *int32      `json:"category_id"`
	SearchText *string     `json:"search_text"`
	ShopID     pgtype.UUID `json:"shop_id"`
}

func (q *Queries) CountDeletedProducts(ctx context.Context, arg CountDeletedProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeletedProducts, arg.CategoryID, arg.SearchText, arg.ShopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products p
WHERE
    ($1::int IS NULL OR EXISTS (SELECT 1 FROM product_categories pc WHERE pc.product_id = p.id AND pc.category_id = $1))
  AND
    ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%')
  AND ($3::uuid IS NULL OR p.shop_id = $3)
  AND p.deleted_at IS NULL
`

type CountProductsParams struct {
	CategoryID *int32      `json:"category_id"`
	SearchText *string     `json:"search_text"`
	ShopID     pgtype.UUID `json:"shop_id"`
}

// Counts total products for pagination, respecting filters.
func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.CategoryID, arg.SearchText, arg.ShopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    name,
    image_url,
    price,
    stock,
    cost_price,
    shop_id
) VALUES (
             $1, $2, $3, $4, $5, $6
         ) RETURNING id, name, image_url, price, stock, created_at, updated_at, deleted_at, cost_price, shop_id
`

type CreateProductParams struct {
	Name      string         `json:"name"`
	ImageUrl  *string        `json:"image_url"`
	Price     int64          `json:"price"`
	Stock     int32          `json:"stock"`
	CostPrice pgtype.Numeric `json:"cost_price"`
	ShopID    pgtype.UUID    `json:"shop_id"`
}

// Queries for Products
//
// Data isolation: catalog-management queries below are scoped by shop_id using the
// lenient pattern `sqlc.narg('shop_id')::uuid IS NULL OR shop_id = sqlc.narg('shop_id')`
// (NULL shop arg = single-tenant behaviour; a real shop = isolation). The
// order/stock mutation path (GetProductsByIDs, DecreaseProductStock, AddProductStock,
// GetProductsForUpdate) and product options remain unscoped for now, as they run
// inside the transactional order flow keyed by already-resolved product ids.
// Creates a new product and returns its full details.
// Product options should be created separately in a transaction.
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.ImageUrl,
		arg.Price,
		arg.Stock,
		arg.CostPrice,
		arg.ShopID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
		&i.ShopID,
	)
	return i, err
}

const createProductOption = `-- name: CreateProductOption :one

INSERT INTO product_options (
    product_id,
    name,
    additional_price,
    image_url
) VALUES (
             $1, $2, $3, $4
         ) RETURNING id, product_id, name, additional_price, image_url, created_at, updated_at, deleted_at
`

type CreateProductOptionParams struct {
	ProductID       uuid.UUID `json:"product_id"`
	Name            string    `json:"name"`
	AdditionalPrice int64     `json:"additional_price"`
	ImageUrl        *string   `json:"image_url"`
}

// Queries for Product Options (Variants)
// Creates a new option for a specific product.
func (q *Queries) CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (ProductOption, error) {
	row := q.db.QueryRow(ctx, createProductOption,
		arg.ProductID,
		arg.Name,
		arg.AdditionalPrice,
		arg.ImageUrl,
	)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.AdditionalPrice,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decreaseProductStock = `-- name: DecreaseProductStock :one
UPDATE products
SET stock = stock - $1
WHERE id = $2
RETURNING id, name, image_url, price, stock, created_at, updated_at, deleted_at, cost_price, shop_id
`

type DecreaseProductStockParams struct {
	Quantity int32     `json:"quantity"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, decreaseProductStock, arg.Quantity, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
		&i.ShopID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
  AND ($2::uuid IS NULL OR shop_id = $2)
`

type DeleteProductParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

// Deletes a product. Its options will be deleted automatically due to 'ON DELETE CASCADE'.
func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.ShopID)
	return err
}

const getDeletedProduct = `-- name: GetDeletedProduct :one
SELECT
    p.id, p.name, p.image_url, p.price, p.stock, p.created_at, p.updated_at, p.deleted_at, p.cost_price, p.shop_id,
    COALESCE(
            (SELECT json_agg(po.*)
             FROM product_options po
             WHERE po.product_id = p.id),
            '[]'::json
    ) AS options
FROM
    products p
WHERE
    p.id = $1
  AND p.deleted_at IS NOT NULL
  AND ($2::uuid IS NULL OR p.shop_id = $2)
LIMIT 1
`

type GetDeletedProductParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

type GetDeletedProductRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	ImageUrl  *string            `json:"image_url"`
	Price     int64              `json:"price"`
	Stock     int32              `json:"stock"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CostPrice pgtype.Numeric     `json:"cost_price"`
	ShopID    pgtype.UUID        `json:"shop_id"`
	Options   interface{}        `json:"options"`
}

func (q *Queries) GetDeletedProduct(ctx context.Context, arg GetDeletedProductParams) (GetDeletedProductRow, error) {
	row := q.db.QueryRow(ctx, getDeletedProduct, arg.ID, arg.ShopID)
	var i GetDeletedProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
		&i.ShopID,
		&i.Options,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id, p.name, p.image_url, p.price, p.stock, p.created_at, p.updated_at, p.deleted_at, p.cost_price, p.shop_id,
    COALESCE(
            (SELECT json_agg(po.*)
             FROM product_options po
             WHERE po.product_id = p.id AND po.deleted_at IS NULL),
            '[]'::json
    ) AS options,
    COALESCE(
        (SELECT json_agg(c.*)
         FROM product_categories pc
         JOIN categories c ON pc.category_id = c.id
         WHERE pc.product_id = p.id),
        '[]'::json
    ) AS categories
FROM
    products p
WHERE
    p.id = $1
  AND p.deleted_at IS NULL
LIMIT 1
`

type GetProductByIDRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	ImageUrl   *string            `json:"image_url"`
	Price      int64              `json:"price"`
	Stock      int32              `json:"stock"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	CostPrice  pgtype.Numeric     `json:"cost_price"`
	ShopID     pgtype.UUID        `json:"shop_id"`
	Options    interface{}        `json:"options"`
	Categories interface{}        `json:"categories"`
}

// Retrieves a product by its ID, including its options.
func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
		&i.ShopID,
		&i.Options,
		&i.Categories,
	)
	return i, err
}

const getProductOption = `-- name: GetProductOption :one
SELECT id, product_id, name, additional_price, image_url, created_at, updated_at, deleted_at FROM product_options
WHERE id = $1 AND product_id = $2
LIMIT 1
`

type GetProductOptionParams struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"product_id"`
}

// Mengambil satu varian produk berdasarkan ID dan ID produk induknya.
func (q *Queries) GetProductOption(ctx context.Context, arg GetProductOptionParams) (ProductOption, error) {
	row := q.db.QueryRow(ctx, getProductOption, arg.ID, arg.ProductID)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.AdditionalPrice,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductOptionByID = `-- name: GetProductOptionByID :one
SELECT
    po.id, po.product_id, po.name, po.additional_price, po.image_url, po.created_at, po.updated_at, po.deleted_at,
    p.name AS product_name,
    p.image_url AS product_image_url,
    p.price AS product_price,
    p.stock AS product_stock
FROM
    product_options po
        JOIN
    products p ON po.product_id = p.id
WHERE
    po.id = $1
  AND po.deleted_at IS NULL
  AND p.deleted_at IS NULL
ORDER BY
    po.name ASC
LIMIT 1
`

type GetProductOptionByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	ProductID       uuid.UUID          `json:"product_id"`
	Name            string             `json:"name"`
	AdditionalPrice int64              `json:"additional_price"`
	ImageUrl        *string            `json:"image_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	ProductName     string             `json:"product_name"`
	ProductImageUrl *string            `json:"product_image_url"`
	ProductPrice    int64              `json:"product_price"`
	ProductStock    int32              `json:"product_stock"`
}

// Retrieves a product option by its ID, including its product details.
func (q *Queries) GetProductOptionByID(ctx context.Context, id uuid.UUID) (GetProductOptionByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductOptionByID, id)
	var i GetProductOptionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.AdditionalPrice,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.ProductImageUrl,
		&i.ProductPrice,
		&i.ProductStock,
	)
	return i, err
}

const getProductOptionsByIDs = `-- name: GetProductOptionsByIDs :many
SELECT id, product_id, name, additional_price, image_url, created_at, updated_at, deleted_at FROM product_options
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetProductOptionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductOption, error) {
	rows, err := q.db.Query(ctx, getProductOptionsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOption{}
	for rows.Next() {
		var i ProductOption
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.AdditionalPrice,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductWithOptions = `-- name: GetProductWithOptions :one
SELECT
    p.id, p.name, p.image_url, p.price, p.stock, p.created_at, p.updated_at, p.deleted_at, p.cost_price, p.shop_id,
    COALESCE(
            (SELECT json_agg(po.*)
             FROM product_options po
             WHERE po.product_id = p.id AND po.deleted_at IS NULL),
            '[]'::json
    ) AS options
FROM
    products p
WHERE
    p.id = $1
  AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR p.shop_id = $2)
LIMIT 1
`

type GetProductWithOptionsParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

type GetProductWithOptionsRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	ImageUrl  *string            `json:"image_url"`
	Price     int64              `json:"price"`
	Stock     int32              `json:"stock"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CostPrice pgtype.Numeric     `json:"cost_price"`
	ShopID    pgtype.UUID        `json:"shop_id"`
	Options   interface{}        `json:"options"`
}

// Retrieves a single product and aggregates its options into a JSON array.
func (q *Queries) GetProductWithOptions(ctx context.Context, arg GetProductWithOptionsParams) (GetProductWithOptionsRow, error) {
	row := q.db.QueryRow(ctx, getProductWithOptions, arg.ID, arg.ShopID)
	var i GetProductWithOptionsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
		&i.ShopID,
		&i.Options,
	)
	return i, err
}

const getProductsByIDs = `-- name: GetProductsByIDs :many
SELECT id, name, image_url, price, stock, created_at, updated_at, deleted_at, cost_price, shop_id FROM products
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetProductsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CostPrice,
			&i.ShopID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForUpdate = `-- name: GetProductsForUpdate :many
SELECT id, name, image_url, price, stock, created_at, updated_at, deleted_at, cost_price, shop_id FROM products
WHERE id = ANY($1::uuid[])
FOR UPDATE
`

func (q *Queries) GetProductsForUpdate(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsForUpdate, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Price,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CostPrice,
			&i.ShopID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedProducts = `-- name: ListDeletedProducts :many
SELECT
    p.id,
    p.name,
    p.price,
    p.stock,
    p.image_url,
    COALESCE(
        (SELECT json_agg(c.*)
         FROM product_categories pc
         JOIN categories c ON pc.category_id = c.id
         WHERE pc.product_id = p.id),
        '[]'::json
    ) AS categories,
    p.deleted_at
FROM
    products p
WHERE
    ($3::int IS NULL OR EXISTS (SELECT 1 FROM product_categories pc WHERE pc.product_id = p.id AND pc.category_id = $3))
  AND
    ($4::text IS NULL OR p.name ILIKE '%' || $4 || '%')
  AND ($5::uuid IS NULL OR p.shop_id = $5)
  AND p.deleted_at IS NOT NULL
ORDER BY
    p.deleted_at DESC
LIMIT $1 OFFSET $2
`

type ListDeletedProductsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CategoryID *int32      `json:"category_id"`
	SearchText *string     `json:"search_text"`
	ShopID     pgtype.UUID `json:"shop_id"`
}

type ListDeletedProductsRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Price      int64              `json:"price"`
	Stock      int32              `json:"stock"`
	ImageUrl   *string            `json:"image_url"`
	Categories interface{}        `json:"categories"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDeletedProducts(ctx context.Context, arg ListDeletedProductsParams) ([]ListDeletedProductsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedProducts,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.SearchText,
		arg.ShopID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedProductsRow{}
	for rows.Next() {
		var i ListDeletedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.Categories,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsForProduct = `-- name: ListOptionsForProduct :many
SELECT id, product_id, name, additional_price, image_url, created_at, updated_at, deleted_at FROM product_options
WHERE product_id = $1
ORDER BY name ASC
`

// Retrieves all options for a single product.
func (q *Queries) ListOptionsForProduct(ctx context.Context, productID uuid.UUID) ([]ProductOption, error) {
	rows, err := q.db.Query(ctx, listOptionsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOption{}
	for rows.Next() {
		var i ProductOption
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.AdditionalPrice,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id,
    p.name,
    p.price,
    p.stock,
    p.image_url,
    COALESCE(
        (SELECT json_agg(c.*)
         FROM product_categories pc
         JOIN categories c ON pc.category_id = c.id
         WHERE pc.product_id = p.id),
        '[]'::json
    ) AS categories
FROM
    products p
WHERE
    ($3::int IS NULL OR EXISTS (SELECT 1 FROM product_categories pc WHERE pc.product_id = p.id AND pc.category_id = $3))
  AND
    ($4::text IS NULL OR p.name ILIKE '%' || $4 || '%')
  AND ($5::uuid IS NULL OR p.shop_id = $5)
  AND p.deleted_at IS NULL
ORDER BY
    p.name ASC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CategoryID *int32      `json:"category_id"`
	SearchText *string     `json:"search_text"`
	ShopID     pgtype.UUID `json:"shop_id"`
}

type ListProductsRow struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Price      int64       `json:"price"`
	Stock      int32       `json:"stock"`
	ImageUrl   *string     `json:"image_url"`
	Categories interface{} `json:"categories"`
}

// Lists products with filtering and pagination.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.SearchText,
		arg.ShopID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProduct = `-- name: RestoreProduct :exec
UPDATE products
SET deleted_at = NULL
WHERE id = $1
  AND ($2::uuid IS NULL OR shop_id = $2)
`

type RestoreProductParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) RestoreProduct(ctx context.Context, arg RestoreProductParams) error {
	_, err := q.db.Exec(ctx, restoreProduct, arg.ID, arg.ShopID)
	return err
}

const restoreProductsBulk = `-- name: RestoreProductsBulk :exec
UPDATE products
SET deleted_at = NULL
WHERE id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR shop_id = $2)
`

type RestoreProductsBulkParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	ShopID  pgtype.UUID `json:"shop_id"`
}

func (q *Queries) RestoreProductsBulk(ctx context.Context, arg RestoreProductsBulkParams) error {
	_, err := q.db.Exec(ctx, restoreProductsBulk, arg.Column1, arg.ShopID)
	return err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR shop_id = $2)
`

type SoftDeleteProductParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.ShopID)
	return err
}

const softDeleteProductOption = `-- name: SoftDeleteProductOption :exec
update product_options
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Deletes a single product option.
func (q *Queries) SoftDeleteProductOption(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProductOption, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = COALESCE($1, name),
    image_url = COALESCE($2, image_url),
    price = COALESCE($3, price),
    stock = COALESCE($4, stock),
    cost_price = COALESCE($5, cost_price)
WHERE
    id = $6
  AND ($7::uuid IS NULL OR shop_id = $7)
RETURNING id, name, image_url, price, stock, created_at, updated_at, deleted_at, cost_price, shop_id
`

type UpdateProductParams struct {
	Name      *string        `json:"name"`
	ImageUrl  *string        `json:"image_url"`
	Price     *int64         `json:"price"`
	Stock     *int32         `json:"stock"`
	CostPrice pgtype.Numeric `json:"cost_price"`
	ID        uuid.UUID      `json:"id"`
	ShopID    pgtype.UUID    `json:"shop_id"`
}

// Updates a product's details. Use COALESCE for optional fields.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.ImageUrl,
		arg.Price,
		arg.Stock,
		arg.CostPrice,
		arg.ID,
		arg.ShopID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
		&i.ShopID,
	)
	return i, err
}

const updateProductOption = `-- name: UpdateProductOption :one
UPDATE product_options
SET
    name = COALESCE($1, name),
    additional_price = COALESCE($2, additional_price),
    image_url = COALESCE($3, image_url)
WHERE
    id = $4
RETURNING id, product_id, name, additional_price, image_url, created_at, updated_at, deleted_at
`

type UpdateProductOptionParams struct {
	Name            *string   `json:"name"`
	AdditionalPrice *int64    `json:"additional_price"`
	ImageUrl        *string   `json:"image_url"`
	ID              uuid.UUID `json:"id"`
}

// Updates a specific product option.
func (q *Queries) UpdateProductOption(ctx context.Context, arg UpdateProductOptionParams) (ProductOption, error) {
	row := q.db.QueryRow(ctx, updateProductOption,
		arg.Name,
		arg.AdditionalPrice,
		arg.ImageUrl,
		arg.ID,
	)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.AdditionalPrice,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
