// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddProductStock(ctx context.Context, arg AddProductStockParams) (Product, error)
	AssignProductCategory(ctx context.Context, arg AssignProductCategoryParams) error
	CheckCategoryExists(ctx context.Context, id int32) (bool, error)
	ClearProductCategories(ctx context.Context, productID uuid.UUID) error
	CountDeletedProducts(ctx context.Context, arg CountDeletedProductsParams) (int64, error)
	// Counts total products for pagination, respecting filters.
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountStockHistoryByProduct(ctx context.Context, productID uuid.UUID) (int64, error)
	// Queries for Products
	//
	// Data isolation: catalog-management queries below are scoped by shop_id using the
	// lenient pattern `sqlc.narg('shop_id')::uuid IS NULL OR shop_id = sqlc.narg('shop_id')`
	// (NULL shop arg = single-tenant behaviour; a real shop = isolation). The
	// order/stock mutation path (GetProductsByIDs, DecreaseProductStock, AddProductStock,
	// GetProductsForUpdate) and product options remain unscoped for now, as they run
	// inside the transactional order flow keyed by already-resolved product ids.
	// Creates a new product and returns its full details.
	// Product options should be created separately in a transaction.
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Queries for Product Options (Variants)
	// Creates a new option for a specific product.
	CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (ProductOption, error)
	CreateStockHistory(ctx context.Context, arg CreateStockHistoryParams) (StockHistory, error)
	DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (Product, error)
	// Deletes a product. Its options will be deleted automatically due to 'ON DELETE CASCADE'.
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	GetDeletedProduct(ctx context.Context, arg GetDeletedProductParams) (GetDeletedProductRow, error)
	// Retrieves a product by its ID, including its options.
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	// Mengambil satu varian produk berdasarkan ID dan ID produk induknya.
	GetProductOption(ctx context.Context, arg GetProductOptionParams) (ProductOption, error)
	// Retrieves a product option by its ID, including its product details.
	GetProductOptionByID(ctx context.Context, id uuid.UUID) (GetProductOptionByIDRow, error)
	GetProductOptionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductOption, error)
	// Retrieves a single product and aggregates its options into a JSON array.
	GetProductWithOptions(ctx context.Context, arg GetProductWithOptionsParams) (GetProductWithOptionsRow, error)
	GetProductsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	GetProductsForUpdate(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	GetStockHistoryByProduct(ctx context.Context, productID uuid.UUID) ([]StockHistory, error)
	GetStockHistoryByProductWithPagination(ctx context.Context, arg GetStockHistoryByProductWithPaginationParams) ([]StockHistory, error)
	ListDeletedProducts(ctx context.Context, arg ListDeletedProductsParams) ([]ListDeletedProductsRow, error)
	// Retrieves all options for a single product.
	ListOptionsForProduct(ctx context.Context, productID uuid.UUID) ([]ProductOption, error)
	// Lists products with filtering and pagination.
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	RestoreProduct(ctx context.Context, arg RestoreProductParams) error
	RestoreProductsBulk(ctx context.Context, arg RestoreProductsBulkParams) error
	SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error
	// Deletes a single product option.
	SoftDeleteProductOption(ctx context.Context, id uuid.UUID) error
	// Updates a product's details. Use COALESCE for optional fields.
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	// Updates a specific product option.
	UpdateProductOption(ctx context.Context, arg UpdateProductOptionParams) (ProductOption, error)
}

var _ Querier = (*Queries)(nil)
