// Code generated by MockGen. DO NOT EDIT.
// Source: POS-fiplex/internal/categories/repository (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_categories_repo.go -mock_names Querier=MockCategoriesRepository POS-fiplex/internal/categories/repository Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	repository "POS-fiplex/internal/categories/repository"
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoriesRepository is a mock of Querier interface.
type MockCategoriesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoriesRepositoryMockRecorder
	isgomock struct{}
}

// MockCategoriesRepositoryMockRecorder is the mock recorder for MockCategoriesRepository.
type MockCategoriesRepositoryMockRecorder struct {
	mock *MockCategoriesRepository
}

// NewMockCategoriesRepository creates a new mock instance.
func NewMockCategoriesRepository(ctrl *gomock.Controller) *MockCategoriesRepository {
	mock := &MockCategoriesRepository{ctrl: ctrl}
	mock.recorder = &MockCategoriesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoriesRepository) EXPECT() *MockCategoriesRepositoryMockRecorder {
	return m.recorder
}

// CountCategories mocks base method.
func (m *MockCategoriesRepository) CountCategories(ctx context.Context, shopID pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCategories", ctx, shopID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCategories indicates an expected call of CountCategories.
func (mr *MockCategoriesRepositoryMockRecorder) CountCategories(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCategories", reflect.TypeOf((*MockCategoriesRepository)(nil).CountCategories), ctx, shopID)
}

// CountProductsInCategory mocks base method.
func (m *MockCategoriesRepository) CountProductsInCategory(ctx context.Context, categoryID int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProductsInCategory", ctx, categoryID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProductsInCategory indicates an expected call of CountProductsInCategory.
func (mr *MockCategoriesRepositoryMockRecorder) CountProductsInCategory(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProductsInCategory", reflect.TypeOf((*MockCategoriesRepository)(nil).CountProductsInCategory), ctx, categoryID)
}

// CreateCategory mocks base method.
func (m *MockCategoriesRepository) CreateCategory(ctx context.Context, arg repository.CreateCategoryParams) (repository.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, arg)
	ret0, _ := ret[0].(repository.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCategoriesRepositoryMockRecorder) CreateCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCategoriesRepository)(nil).CreateCategory), ctx, arg)
}

// DeleteCategory mocks base method.
func (m *MockCategoriesRepository) DeleteCategory(ctx context.Context, arg repository.DeleteCategoryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockCategoriesRepositoryMockRecorder) DeleteCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockCategoriesRepository)(nil).DeleteCategory), ctx, arg)
}

// ExistsCategory mocks base method.
func (m *MockCategoriesRepository) ExistsCategory(ctx context.Context, arg repository.ExistsCategoryParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsCategory", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsCategory indicates an expected call of ExistsCategory.
func (mr *MockCategoriesRepositoryMockRecorder) ExistsCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsCategory", reflect.TypeOf((*MockCategoriesRepository)(nil).ExistsCategory), ctx, arg)
}

// GetCategory mocks base method.
func (m *MockCategoriesRepository) GetCategory(ctx context.Context, arg repository.GetCategoryParams) (repository.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", ctx, arg)
	ret0, _ := ret[0].(repository.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockCategoriesRepositoryMockRecorder) GetCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockCategoriesRepository)(nil).GetCategory), ctx, arg)
}

// ListCategories mocks base method.
func (m *MockCategoriesRepository) ListCategories(ctx context.Context, arg repository.ListCategoriesParams) ([]repository.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, arg)
	ret0, _ := ret[0].([]repository.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockCategoriesRepositoryMockRecorder) ListCategories(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockCategoriesRepository)(nil).ListCategories), ctx, arg)
}

// ListCategoriesWithProducts mocks base method.
func (m *MockCategoriesRepository) ListCategoriesWithProducts(ctx context.Context, arg repository.ListCategoriesWithProductsParams) ([]repository.ListCategoriesWithProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoriesWithProducts", ctx, arg)
	ret0, _ := ret[0].([]repository.ListCategoriesWithProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoriesWithProducts indicates an expected call of ListCategoriesWithProducts.
func (mr *MockCategoriesRepositoryMockRecorder) ListCategoriesWithProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoriesWithProducts", reflect.TypeOf((*MockCategoriesRepository)(nil).ListCategoriesWithProducts), ctx, arg)
}

// UpdateCategory mocks base method.
func (m *MockCategoriesRepository) UpdateCategory(ctx context.Context, arg repository.UpdateCategoryParams) (repository.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, arg)
	ret0, _ := ret[0].(repository.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockCategoriesRepositoryMockRecorder) UpdateCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockCategoriesRepository)(nil).UpdateCategory), ctx, arg)
}
