// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM customers
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR shop_id = $1)
`

func (q *Queries) CountCustomers(ctx context.Context, shopID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, phone, email, address, shop_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, phone, email, address, created_at, updated_at, deleted_at, shop_id
`

type CreateCustomerParams struct {
	Name    string      `json:"name"`
	Phone   *string     `json:"phone"`
	Email   *string     `json:"email"`
	Address *string     `json:"address"`
	ShopID  pgtype.UUID `json:"shop_id"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.ShopID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ShopID,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
UPDATE customers SET deleted_at = NOW()
WHERE id = $1
  AND ($2::uuid IS NULL OR shop_id = $2)
`

type DeleteCustomerParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, deleteCustomer, arg.ID, arg.ShopID)
	return err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, phone, email, address, created_at, updated_at, deleted_at, shop_id FROM customers
WHERE id = $1 AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR shop_id = $2)
`

type GetCustomerByIDParams struct {
	ID     uuid.UUID   `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.ShopID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ShopID,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, phone, email, address, created_at, updated_at, deleted_at, shop_id FROM customers
WHERE deleted_at IS NULL
  AND ($3::uuid IS NULL OR shop_id = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ShopID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $2, phone = $3, email = $4, address = $5, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
  AND ($6::uuid IS NULL OR shop_id = $6)
RETURNING id, name, phone, email, address, created_at, updated_at, deleted_at, shop_id
`

type UpdateCustomerParams struct {
	ID      uuid.UUID   `json:"id"`
	Name    string      `json:"name"`
	Phone   *string     `json:"phone"`
	Email   *string     `json:"email"`
	Address *string     `json:"address"`
	ShopID  pgtype.UUID `json:"shop_id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.ShopID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ShopID,
	)
	return i, err
}
