// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCustomers(ctx context.Context, shopID pgtype.UUID) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
