// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM categories
WHERE ($1::uuid IS NULL OR shop_id = $1)
`

func (q *Queries) CountCategories(ctx context.Context, shopID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, shopID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsInCategory = `-- name: CountProductsInCategory :one
SELECT count(*) FROM product_categories WHERE category_id = $1
`

func (q *Queries) CountProductsInCategory(ctx context.Context, categoryID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsInCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, shop_id)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at, shop_id
`

type CreateCategoryParams struct {
	Name   string      `json:"name"`
	ShopID pgtype.UUID `json:"shop_id"`
}

// Create a new category, tagged with the active shop (nullable during transition).
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.ShopID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShopID,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE
FROM categories
WHERE id = $1
  AND ($2::uuid IS NULL OR shop_id = $2)
`

type DeleteCategoryParams struct {
	ID     int32       `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.ShopID)
	return err
}

const existsCategory = `-- name: ExistsCategory :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE id = $1
      AND ($2::uuid IS NULL OR shop_id = $2)
)
`

type ExistsCategoryParams struct {
	ID     int32       `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) ExistsCategory(ctx context.Context, arg ExistsCategoryParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsCategory, arg.ID, arg.ShopID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, created_at, updated_at, shop_id
FROM categories
WHERE id = $1
  AND ($2::uuid IS NULL OR shop_id = $2)
LIMIT 1
`

type GetCategoryParams struct {
	ID     int32       `json:"id"`
	ShopID pgtype.UUID `json:"shop_id"`
}

// Fetch a single category by ID, scoped to the active shop.
// Lenient scope: when no shop is active (shop_id arg NULL) all rows are visible,
// preserving single-tenant behaviour; when a shop is active, isolation applies.
func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.ShopID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShopID,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, created_at, updated_at, shop_id
FROM categories
WHERE ($3::uuid IS NULL OR shop_id = $3)
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Limit, arg.Offset, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShopID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithProducts = `-- name: ListCategoriesWithProducts :many
SELECT c.id, c.name, c.created_at, c.updated_at, COUNT(pc.product_id) AS product_count
FROM categories c
LEFT JOIN product_categories pc ON c.id = pc.category_id
WHERE ($3::uuid IS NULL OR c.shop_id = $3)
GROUP BY c.id
ORDER BY c.name ASC
LIMIT $1 OFFSET $2
`

type ListCategoriesWithProductsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	ShopID pgtype.UUID `json:"shop_id"`
}

type ListCategoriesWithProductsRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProductCount int64              `json:"product_count"`
}

func (q *Queries) ListCategoriesWithProducts(ctx context.Context, arg ListCategoriesWithProductsParams) ([]ListCategoriesWithProductsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithProducts, arg.Limit, arg.Offset, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithProductsRow{}
	for rows.Next() {
		var i ListCategoriesWithProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2
WHERE id = $1
  AND ($3::uuid IS NULL OR shop_id = $3)
RETURNING id, name, created_at, updated_at, shop_id
`

type UpdateCategoryParams struct {
	ID     int32       `json:"id"`
	Name   string      `json:"name"`
	ShopID pgtype.UUID `json:"shop_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.ShopID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShopID,
	)
	return i, err
}
