// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCategories(ctx context.Context, shopID pgtype.UUID) (int64, error)
	CountProductsInCategory(ctx context.Context, categoryID int32) (int64, error)
	// Create a new category, tagged with the active shop (nullable during transition).
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	ExistsCategory(ctx context.Context, arg ExistsCategoryParams) (bool, error)
	// Fetch a single category by ID, scoped to the active shop.
	// Lenient scope: when no shop is active (shop_id arg NULL) all rows are visible,
	// preserving single-tenant behaviour; when a shop is active, isolation applies.
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListCategoriesWithProducts(ctx context.Context, arg ListCategoriesWithProductsParams) ([]ListCategoriesWithProductsRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
}

var _ Querier = (*Queries)(nil)
